language: python
cache: pip
python: "3.7"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "joostlek-github"
    token: $SONAR_TOKEN
script:
  - pytest
  - sonar-scanner