sudo: required
language: python
cache: pip
python: "3.7"
services:
  - docker
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "joostlek-github"
    token: $SONAR_TOKEN
script:
  - pytest
  - sonar-scanner
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "python" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=joostlek/hermes-client
  - docker build -t $IMAGE_NAME:$TAG .
  - docker push $IMAGE_NAME